{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "athena-tts.fullname" . }}
  labels:
    {{- include "athena-tts.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- if .Values.ingress.tls.enabled }}
    - websecure
    {{- else }}
    - web
    {{- end }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "athena-tts.fullname" . }}
          port: {{ .Values.service.port }}
      {{- if .Values.ingress.middlewares }}
      middlewares:
        {{- toYaml .Values.ingress.middlewares | nindent 8 }}
      {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "athena-tts.fullname" .)) }}
  {{- end }}
{{- end }}
---
{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "athena-tts.fullname" . }}-tls
  labels:
    {{- include "athena-tts.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "athena-tts.fullname" .)) }}
  issuerRef:
    name: {{ .Values.ingress.tls.certManager.issuer }}
    kind: {{ .Values.ingress.tls.certManager.issuerKind }}
  dnsNames:
    - {{ .Values.ingress.host }}
{{- end }}
