apiVersion: v1
kind: Secret
metadata:
  name: {{ include "athena-tts.fullname" . }}-agent
  labels:
    {{- include "athena-tts.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.agent.key | b64enc | quote }}
